services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ../auth-service/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  app:
    build: ../auth-service/backend
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  applicant-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_APPLICANT_NAME}
    ports:
      - "5434:5432"
  applicant-service:
    build: ../applicant-service/backend
    ports:
      - "8082:8082"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_APPLICANT_NAME}
      - DB_HOST=applicant-db
      - DB_PORT=5432
    depends_on:
      - applicant-db